
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

# Add python script feature
python_script:
# Example configuration.yaml entry
# Add recorder feature
recorder:
    auto_purge: true
    purge_keep_days: 5

# Add logger feature
logger:
    default: info
    logs:
        homeassistant.components.yamaha: critical
        custom_components.my_integration: critical
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
switch: !include switch.yaml
climate: !include climate.yaml
#http:
#    base_url: https://cluboslo.duckdns.org
#    ssl_certificate: /ssl/fullchain.pem
#    ssl_key: /ssl/privkey.pem
shell_command:
    # Command to update DDNS with public IP address
    Open_Gate: '/usr/local/bin/testGate.py'
